version: '3.4'

services:
  upload-pypi:
    build:
      context: ./
      target: rasgoql
    working_dir: /var/lib/rasgoql/mount/rasgoql
    command: ./scripts/publish-pypi.sh pypi
    environment:
      PYPI_USER: ${PYPI_USER}
      PYPI_PASSWORD: ${PYPI_PASSWORD}
    volumes:
      - ./:/var/lib/rasgoql/mount/

  test-pypi:
    build:
      context: ./
      target: rasgoql
    working_dir: /var/lib/rasgoql/mount/rasgoql
    command: ./scripts/publish-pypi.sh pypitest
    environment:
      PYPITEST_USER: ${PYPITEST_USER}
      PYPITEST_PASSWORD: ${PYPITEST_PASSWORD}
    volumes:
      - ./:/var/lib/rasgoql/mount/
