version: '3.4'

services:
  upload:
    build:
      context: ./
      target: rasgoql
    working_dir: /var/lib/rasgo/mount/rasgoql
    command: ./bin/publish-pypi.sh pypi
    environment:
      PYPI_USER: ${PYPI_USER}
      PYPI_PASSWORD: ${PYPI_PASSWORD}
    volumes:
      - ./:/var/lib/rasgo/mount/